'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Runtime.Serialization

'
'This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
'
Namespace ZZAzureServices
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="WebResult", [Namespace]:="http://schemas.datacontract.org/2004/07/Bing")>  _
    Partial Public Class WebResult
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private DescriptionField As String
        
        Private DisplayUrlField As String
        
        Private IDField As System.Guid
        
        Private TitleField As String
        
        Private UrlField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Description() As String
            Get
                Return Me.DescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescriptionField, value) <> true) Then
                    Me.DescriptionField = value
                    Me.RaisePropertyChanged("Description")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DisplayUrl() As String
            Get
                Return Me.DisplayUrlField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DisplayUrlField, value) <> true) Then
                    Me.DisplayUrlField = value
                    Me.RaisePropertyChanged("DisplayUrl")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID() As System.Guid
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Title() As String
            Get
                Return Me.TitleField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TitleField, value) <> true) Then
                    Me.TitleField = value
                    Me.RaisePropertyChanged("Title")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Url() As String
            Get
                Return Me.UrlField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UrlField, value) <> true) Then
                    Me.UrlField = value
                    Me.RaisePropertyChanged("Url")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ImageResult", [Namespace]:="http://schemas.datacontract.org/2004/07/Bing")>  _
    Partial Public Class ImageResult
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private ContentTypeField As String
        
        Private DisplayUrlField As String
        
        Private FileSizeField As System.Nullable(Of Long)
        
        Private HeightField As System.Nullable(Of Integer)
        
        Private IDField As System.Guid
        
        Private MediaUrlField As String
        
        Private SourceUrlField As String
        
        Private ThumbnailField As ZZAzureServices.Thumbnail
        
        Private TitleField As String
        
        Private WidthField As System.Nullable(Of Integer)
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ContentType() As String
            Get
                Return Me.ContentTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ContentTypeField, value) <> true) Then
                    Me.ContentTypeField = value
                    Me.RaisePropertyChanged("ContentType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DisplayUrl() As String
            Get
                Return Me.DisplayUrlField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DisplayUrlField, value) <> true) Then
                    Me.DisplayUrlField = value
                    Me.RaisePropertyChanged("DisplayUrl")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FileSize() As System.Nullable(Of Long)
            Get
                Return Me.FileSizeField
            End Get
            Set
                If (Me.FileSizeField.Equals(value) <> true) Then
                    Me.FileSizeField = value
                    Me.RaisePropertyChanged("FileSize")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Height() As System.Nullable(Of Integer)
            Get
                Return Me.HeightField
            End Get
            Set
                If (Me.HeightField.Equals(value) <> true) Then
                    Me.HeightField = value
                    Me.RaisePropertyChanged("Height")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID() As System.Guid
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MediaUrl() As String
            Get
                Return Me.MediaUrlField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MediaUrlField, value) <> true) Then
                    Me.MediaUrlField = value
                    Me.RaisePropertyChanged("MediaUrl")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SourceUrl() As String
            Get
                Return Me.SourceUrlField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SourceUrlField, value) <> true) Then
                    Me.SourceUrlField = value
                    Me.RaisePropertyChanged("SourceUrl")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Thumbnail() As ZZAzureServices.Thumbnail
            Get
                Return Me.ThumbnailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ThumbnailField, value) <> true) Then
                    Me.ThumbnailField = value
                    Me.RaisePropertyChanged("Thumbnail")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Title() As String
            Get
                Return Me.TitleField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TitleField, value) <> true) Then
                    Me.TitleField = value
                    Me.RaisePropertyChanged("Title")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Width() As System.Nullable(Of Integer)
            Get
                Return Me.WidthField
            End Get
            Set
                If (Me.WidthField.Equals(value) <> true) Then
                    Me.WidthField = value
                    Me.RaisePropertyChanged("Width")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Thumbnail", [Namespace]:="http://schemas.datacontract.org/2004/07/Bing")>  _
    Partial Public Class Thumbnail
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private ContentTypeField As String
        
        Private FileSizeField As System.Nullable(Of Long)
        
        Private HeightField As System.Nullable(Of Integer)
        
        Private MediaUrlField As String
        
        Private WidthField As System.Nullable(Of Integer)
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ContentType() As String
            Get
                Return Me.ContentTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ContentTypeField, value) <> true) Then
                    Me.ContentTypeField = value
                    Me.RaisePropertyChanged("ContentType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FileSize() As System.Nullable(Of Long)
            Get
                Return Me.FileSizeField
            End Get
            Set
                If (Me.FileSizeField.Equals(value) <> true) Then
                    Me.FileSizeField = value
                    Me.RaisePropertyChanged("FileSize")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Height() As System.Nullable(Of Integer)
            Get
                Return Me.HeightField
            End Get
            Set
                If (Me.HeightField.Equals(value) <> true) Then
                    Me.HeightField = value
                    Me.RaisePropertyChanged("Height")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MediaUrl() As String
            Get
                Return Me.MediaUrlField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MediaUrlField, value) <> true) Then
                    Me.MediaUrlField = value
                    Me.RaisePropertyChanged("MediaUrl")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Width() As System.Nullable(Of Integer)
            Get
                Return Me.WidthField
            End Get
            Set
                If (Me.WidthField.Equals(value) <> true) Then
                    Me.WidthField = value
                    Me.RaisePropertyChanged("Width")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AnalyzedCorpus", [Namespace]:="http://schemas.datacontract.org/2004/07/WCFServiceWebRole")>  _
    Partial Public Class AnalyzedCorpus
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private AnalyzedTextField As String
        
        Private EntitesListField As System.Collections.ObjectModel.ObservableCollection(Of ZZAzureServices.NamedEntity)
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AnalyzedText() As String
            Get
                Return Me.AnalyzedTextField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AnalyzedTextField, value) <> true) Then
                    Me.AnalyzedTextField = value
                    Me.RaisePropertyChanged("AnalyzedText")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EntitesList() As System.Collections.ObjectModel.ObservableCollection(Of ZZAzureServices.NamedEntity)
            Get
                Return Me.EntitesListField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EntitesListField, value) <> true) Then
                    Me.EntitesListField = value
                    Me.RaisePropertyChanged("EntitesList")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="NamedEntity", [Namespace]:="http://nlptoolkit.cloudapp.net")>  _
    Partial Public Class NamedEntity
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private NamedEntityPhraseField As String
        
        Private StartPositionField As UInteger
        
        Private LengthField As UInteger
        
        Private ConfidenceField As Double
        
        Private NamedEntityTypeField As ZZAzureServices.NamedEntityType
        
        Private NamedEntityWordsField As System.Collections.ObjectModel.ObservableCollection(Of ZZAzureServices.Word)
        
        Private SentenceIdField As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property NamedEntityPhrase() As String
            Get
                Return Me.NamedEntityPhraseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NamedEntityPhraseField, value) <> true) Then
                    Me.NamedEntityPhraseField = value
                    Me.RaisePropertyChanged("NamedEntityPhrase")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property StartPosition() As UInteger
            Get
                Return Me.StartPositionField
            End Get
            Set
                If (Me.StartPositionField.Equals(value) <> true) Then
                    Me.StartPositionField = value
                    Me.RaisePropertyChanged("StartPosition")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property Length() As UInteger
            Get
                Return Me.LengthField
            End Get
            Set
                If (Me.LengthField.Equals(value) <> true) Then
                    Me.LengthField = value
                    Me.RaisePropertyChanged("Length")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property Confidence() As Double
            Get
                Return Me.ConfidenceField
            End Get
            Set
                If (Me.ConfidenceField.Equals(value) <> true) Then
                    Me.ConfidenceField = value
                    Me.RaisePropertyChanged("Confidence")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property NamedEntityType() As ZZAzureServices.NamedEntityType
            Get
                Return Me.NamedEntityTypeField
            End Get
            Set
                If (Me.NamedEntityTypeField.Equals(value) <> true) Then
                    Me.NamedEntityTypeField = value
                    Me.RaisePropertyChanged("NamedEntityType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property NamedEntityWords() As System.Collections.ObjectModel.ObservableCollection(Of ZZAzureServices.Word)
            Get
                Return Me.NamedEntityWordsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NamedEntityWordsField, value) <> true) Then
                    Me.NamedEntityWordsField = value
                    Me.RaisePropertyChanged("NamedEntityWords")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=6)>  _
        Public Property SentenceId() As Integer
            Get
                Return Me.SentenceIdField
            End Get
            Set
                If (Me.SentenceIdField.Equals(value) <> true) Then
                    Me.SentenceIdField = value
                    Me.RaisePropertyChanged("SentenceId")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="NamedEntityType", [Namespace]:="http://nlptoolkit.cloudapp.net")>  _
    Public Enum NamedEntityType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Human = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Location = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Organization = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NotNamedEntity = 3
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Word", [Namespace]:="http://nlptoolkit.cloudapp.net")>  _
    Partial Public Class Word
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private WordStringField As String
        
        Private NormalizedWordField As String
        
        Private FlagsField As ZZAzureServices.FlagCollection
        
        Private PositionField As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property WordString() As String
            Get
                Return Me.WordStringField
            End Get
            Set
                If (Object.ReferenceEquals(Me.WordStringField, value) <> true) Then
                    Me.WordStringField = value
                    Me.RaisePropertyChanged("WordString")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property NormalizedWord() As String
            Get
                Return Me.NormalizedWordField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NormalizedWordField, value) <> true) Then
                    Me.NormalizedWordField = value
                    Me.RaisePropertyChanged("NormalizedWord")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property Flags() As ZZAzureServices.FlagCollection
            Get
                Return Me.FlagsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FlagsField, value) <> true) Then
                    Me.FlagsField = value
                    Me.RaisePropertyChanged("Flags")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property Position() As Integer
            Get
                Return Me.PositionField
            End Get
            Set
                If (Me.PositionField.Equals(value) <> true) Then
                    Me.PositionField = value
                    Me.RaisePropertyChanged("Position")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="FlagCollection", [Namespace]:="http://nlptoolkit.cloudapp.net")>  _
    Partial Public Class FlagCollection
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private ItemsField As System.Collections.ObjectModel.ObservableCollection(Of ZZAzureServices.FlagInfo)
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Items() As System.Collections.ObjectModel.ObservableCollection(Of ZZAzureServices.FlagInfo)
            Get
                Return Me.ItemsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ItemsField, value) <> true) Then
                    Me.ItemsField = value
                    Me.RaisePropertyChanged("Items")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="FlagInfo", [Namespace]:="http://nlptoolkit.cloudapp.net")>  _
    Partial Public Class FlagInfo
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private FlagField As String
        
        Private RuleIndexField As Integer
        
        Private ConfidenceField As Double
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Flag() As String
            Get
                Return Me.FlagField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FlagField, value) <> true) Then
                    Me.FlagField = value
                    Me.RaisePropertyChanged("Flag")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property RuleIndex() As Integer
            Get
                Return Me.RuleIndexField
            End Get
            Set
                If (Me.RuleIndexField.Equals(value) <> true) Then
                    Me.RuleIndexField = value
                    Me.RaisePropertyChanged("RuleIndex")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property Confidence() As Double
            Get
                Return Me.ConfidenceField
            End Get
            Set
                If (Me.ConfidenceField.Equals(value) <> true) Then
                    Me.ConfidenceField = value
                    Me.RaisePropertyChanged("Confidence")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ZZAzureServices.IHopeService")>  _
    Public Interface IHopeService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHopeService/WebSearch", ReplyAction:="http://tempuri.org/IHopeService/WebSearchResponse")>  _
        Function WebSearchAsync(ByVal query As String, ByVal resultReturn As Integer) As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of ZZAzureServices.WebResult))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHopeService/ImageSearch", ReplyAction:="http://tempuri.org/IHopeService/ImageSearchResponse")>  _
        Function ImageSearchAsync(ByVal query As String, ByVal resultReturn As Integer) As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of ZZAzureServices.ImageResult))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHopeService/CorpusAnalyzer", ReplyAction:="http://tempuri.org/IHopeService/CorpusAnalyzerResponse")>  _
        Function CorpusAnalyzerAsync(ByVal query As String) As System.Threading.Tasks.Task(Of ZZAzureServices.AnalyzedCorpus)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IHopeServiceChannel
        Inherits ZZAzureServices.IHopeService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class HopeServiceClient
        Inherits System.ServiceModel.ClientBase(Of ZZAzureServices.IHopeService)
        Implements ZZAzureServices.IHopeService
        
        ''' <summary>
        ''' Implement this partial method to configure the service endpoint.
        ''' </summary>
        ''' <param name="serviceEndpoint">The endpoint to configure</param>
        ''' <param name="clientCredentials">The client credentials</param>
        Partial Private Shared Sub ConfigureEndpoint(ByVal serviceEndpoint As System.ServiceModel.Description.ServiceEndpoint, ByVal clientCredentials As System.ServiceModel.Description.ClientCredentials)
        End Sub
        
        Public Sub New()
            MyBase.New(HopeServiceClient.GetDefaultBinding, HopeServiceClient.GetDefaultEndpointAddress)
            Me.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IHopeService.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal endpointConfiguration As EndpointConfiguration)
            MyBase.New(HopeServiceClient.GetBindingForEndpoint(endpointConfiguration), HopeServiceClient.GetEndpointAddress(endpointConfiguration))
            Me.Endpoint.Name = endpointConfiguration.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal endpointConfiguration As EndpointConfiguration, ByVal remoteAddress As String)
            MyBase.New(HopeServiceClient.GetBindingForEndpoint(endpointConfiguration), New System.ServiceModel.EndpointAddress(remoteAddress))
            Me.Endpoint.Name = endpointConfiguration.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal endpointConfiguration As EndpointConfiguration, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(HopeServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
            Me.Endpoint.Name = endpointConfiguration.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function WebSearchAsync(ByVal query As String, ByVal resultReturn As Integer) As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of ZZAzureServices.WebResult)) Implements ZZAzureServices.IHopeService.WebSearchAsync
            Return MyBase.Channel.WebSearchAsync(query, resultReturn)
        End Function
        
        Public Function ImageSearchAsync(ByVal query As String, ByVal resultReturn As Integer) As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of ZZAzureServices.ImageResult)) Implements ZZAzureServices.IHopeService.ImageSearchAsync
            Return MyBase.Channel.ImageSearchAsync(query, resultReturn)
        End Function
        
        Public Function CorpusAnalyzerAsync(ByVal query As String) As System.Threading.Tasks.Task(Of ZZAzureServices.AnalyzedCorpus) Implements ZZAzureServices.IHopeService.CorpusAnalyzerAsync
            Return MyBase.Channel.CorpusAnalyzerAsync(query)
        End Function
        
        Public Overridable Function OpenAsync() As System.Threading.Tasks.Task
            Return System.Threading.Tasks.Task.Factory.FromAsync(CType(Me,System.ServiceModel.ICommunicationObject).BeginOpen(Nothing, Nothing), AddressOf CType(Me,System.ServiceModel.ICommunicationObject).EndOpen)
        End Function
        
        Public Overridable Function CloseAsync() As System.Threading.Tasks.Task
            Return System.Threading.Tasks.Task.Factory.FromAsync(CType(Me,System.ServiceModel.ICommunicationObject).BeginClose(Nothing, Nothing), AddressOf CType(Me,System.ServiceModel.ICommunicationObject).EndClose)
        End Function
        
        Private Shared Function GetBindingForEndpoint(ByVal endpointConfiguration As EndpointConfiguration) As System.ServiceModel.Channels.Binding
            If (endpointConfiguration = EndpointConfiguration.BasicHttpBinding_IHopeService) Then
                Dim result As System.ServiceModel.BasicHttpBinding = New System.ServiceModel.BasicHttpBinding()
                result.MaxBufferSize = Integer.MaxValue
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max
                result.MaxReceivedMessageSize = Integer.MaxValue
                result.AllowCookies = true
                Return result
            End If
            Throw New System.InvalidOperationException(String.Format("Could not find endpoint with name '{0}'.", endpointConfiguration))
        End Function
        
        Private Shared Function GetEndpointAddress(ByVal endpointConfiguration As EndpointConfiguration) As System.ServiceModel.EndpointAddress
            If (endpointConfiguration = EndpointConfiguration.BasicHttpBinding_IHopeService) Then
                Return New System.ServiceModel.EndpointAddress("http://api.developers.ps/HopeService.svc")
            End If
            Throw New System.InvalidOperationException(String.Format("Could not find endpoint with name '{0}'.", endpointConfiguration))
        End Function
        
        Private Shared Function GetDefaultBinding() As System.ServiceModel.Channels.Binding
            Return HopeServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IHopeService)
        End Function
        
        Private Shared Function GetDefaultEndpointAddress() As System.ServiceModel.EndpointAddress
            Return HopeServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IHopeService)
        End Function
        
        Public Enum EndpointConfiguration
            
            BasicHttpBinding_IHopeService
        End Enum
    End Class
End Namespace
