//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole.MyClasses
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HaifaDBEntities : DbContext
    {
        public HaifaDBEntities()
            : base("name=HaifaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<arabizedWords> arabizedWords { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<GrammarRules> GrammarRules { get; set; }
        public virtual DbSet<interpretationn> interpretationn { get; set; }
        public virtual DbSet<Prefixes> Prefixes { get; set; }
        public virtual DbSet<ProperNouns> ProperNouns { get; set; }
        public virtual DbSet<roots> roots { get; set; }
        public virtual DbSet<S_No_QuestionWords> S_No_QuestionWords { get; set; }
        public virtual DbSet<S_NoWords> S_NoWords { get; set; }
        public virtual DbSet<S_QuestionWords> S_QuestionWords { get; set; }
        public virtual DbSet<STOPWORDS> STOPWORDS { get; set; }
        public virtual DbSet<Suffixes> Suffixes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TwoWords> TwoWords { get; set; }
        public virtual DbSet<VerbsRoot> VerbsRoot { get; set; }
        public virtual DbSet<W2> W2 { get; set; }
        public virtual DbSet<WordMovements> WordMovements { get; set; }
        public virtual DbSet<Words> Words { get; set; }
        public virtual DbSet<WordTemplates> WordTemplates { get; set; }
        public virtual DbSet<SpecialWords> SpecialWords { get; set; }
    }
}
