//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole.MyClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProperNouns
    {
        public string Word { get; set; }
        public string Diacritics { get; set; }
        public string Meaning { get; set; }
        public Nullable<bool> IsTerminology { get; set; }
    }
}
