//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole.MyClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class roots
    {
        public int ID { get; set; }
        public string Root { get; set; }
        public string Rules { get; set; }
        public string Others { get; set; }
    }
}
