//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole.MyClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialWords
    {
        public int id { get; set; }
        public string Word { get; set; }
        public string diacritics { get; set; }
        public string Meaning { get; set; }
        public string Class { get; set; }
        public string Description { get; set; }
        public string Replacer { get; set; }
    }
}
