//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole.MyClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordTemplates
    {
        public string Template { get; set; }
        public string Tashkeel { get; set; }
        public string Mask { get; set; }
        public string Class { get; set; }
        public string ف { get; set; }
        public string ع { get; set; }
        public string ل { get; set; }
        public string Rule { get; set; }
    }
}
