//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole.ATK {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpellerErrorCode", Namespace="http://nlptoolkit.cloudapp.net")]
    public enum SpellerErrorCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorNonInitialized = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorAccessDenied = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorQuotaExceeded = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorAuthintication = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorMaxLengthExceeded = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorUnknown = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorInvalidMode = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorInvalidParameter = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorDataFileNotFound = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorFailedToLoadData = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorFailedToSaveData = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorInsufficientResources = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorSarfDllMissing = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorFastMorphFailedToLoad = 14,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErroneousWord", Namespace="http://nlptoolkit.cloudapp.net")]
    [System.SerializableAttribute()]
    public partial class ErroneousWord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFServiceWebRole.ATK.Correction[] CorrectionsField;
        
        private int PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WCFServiceWebRole.ATK.Correction[] Corrections {
            get {
                return this.CorrectionsField;
            }
            set {
                if ((object.ReferenceEquals(this.CorrectionsField, value) != true)) {
                    this.CorrectionsField = value;
                    this.RaisePropertyChanged("Corrections");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Position {
            get {
                return this.PositionField;
            }
            set {
                if ((this.PositionField.Equals(value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Word {
            get {
                return this.WordField;
            }
            set {
                if ((object.ReferenceEquals(this.WordField, value) != true)) {
                    this.WordField = value;
                    this.RaisePropertyChanged("Word");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Correction", Namespace="http://nlptoolkit.cloudapp.net")]
    [System.SerializableAttribute()]
    public partial class Correction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorrectionTextField;
        
        private WCFServiceWebRole.ATK.CorrectionType CorrectionTypeField;
        
        private int PositionInCorrectedTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CorrectionText {
            get {
                return this.CorrectionTextField;
            }
            set {
                if ((object.ReferenceEquals(this.CorrectionTextField, value) != true)) {
                    this.CorrectionTextField = value;
                    this.RaisePropertyChanged("CorrectionText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFServiceWebRole.ATK.CorrectionType CorrectionType {
            get {
                return this.CorrectionTypeField;
            }
            set {
                if ((this.CorrectionTypeField.Equals(value) != true)) {
                    this.CorrectionTypeField = value;
                    this.RaisePropertyChanged("CorrectionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PositionInCorrectedText {
            get {
                return this.PositionInCorrectedTextField;
            }
            set {
                if ((this.PositionInCorrectedTextField.Equals(value) != true)) {
                    this.PositionInCorrectedTextField = value;
                    this.RaisePropertyChanged("PositionInCorrectedText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CorrectionType", Namespace="http://nlptoolkit.cloudapp.net")]
    public enum CorrectionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CORRECTION_TYPE_AUTO = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CORRECTION_TYPE_SPELLING = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CORRECTION_TYPE_CONTEXTUAL = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SuggestionOption", Namespace="http://nlptoolkit.cloudapp.net")]
    public enum SuggestionOption : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AutoCorrections = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SpellingCorrections = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AllCorrections = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nlptoolkit.cloudapp.net", ConfigurationName="ATK.ISpellerService")]
    public interface ISpellerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nlptoolkit.cloudapp.net/ISpellerService/DetectMistakes", ReplyAction="http://nlptoolkit.cloudapp.net/ISpellerService/DetectMistakesResponse")]
        WCFServiceWebRole.ATK.DetectMistakesResponse DetectMistakes(WCFServiceWebRole.ATK.DetectMistakesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nlptoolkit.cloudapp.net/ISpellerService/DetectMistakes", ReplyAction="http://nlptoolkit.cloudapp.net/ISpellerService/DetectMistakesResponse")]
        System.Threading.Tasks.Task<WCFServiceWebRole.ATK.DetectMistakesResponse> DetectMistakesAsync(WCFServiceWebRole.ATK.DetectMistakesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nlptoolkit.cloudapp.net/ISpellerService/SuggestCorrections", ReplyAction="http://nlptoolkit.cloudapp.net/ISpellerService/SuggestCorrectionsResponse")]
        WCFServiceWebRole.ATK.SuggestCorrectionsResponse SuggestCorrections(WCFServiceWebRole.ATK.SuggestCorrectionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nlptoolkit.cloudapp.net/ISpellerService/SuggestCorrections", ReplyAction="http://nlptoolkit.cloudapp.net/ISpellerService/SuggestCorrectionsResponse")]
        System.Threading.Tasks.Task<WCFServiceWebRole.ATK.SuggestCorrectionsResponse> SuggestCorrectionsAsync(WCFServiceWebRole.ATK.SuggestCorrectionsRequest request);
        
        // CODEGEN: Generating message contract since element name appId from namespace http://nlptoolkit.cloudapp.net is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nlptoolkit.cloudapp.net/ISpellerService/ReportCorrectionSelection", ReplyAction="http://nlptoolkit.cloudapp.net/ISpellerService/ReportCorrectionSelectionResponse")]
        WCFServiceWebRole.ATK.ReportCorrectionSelectionResponse ReportCorrectionSelection(WCFServiceWebRole.ATK.ReportCorrectionSelectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nlptoolkit.cloudapp.net/ISpellerService/ReportCorrectionSelection", ReplyAction="http://nlptoolkit.cloudapp.net/ISpellerService/ReportCorrectionSelectionResponse")]
        System.Threading.Tasks.Task<WCFServiceWebRole.ATK.ReportCorrectionSelectionResponse> ReportCorrectionSelectionAsync(WCFServiceWebRole.ATK.ReportCorrectionSelectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nlptoolkit.cloudapp.net/ISpellerService/SuggestCorrectionForSpecificWord", ReplyAction="http://nlptoolkit.cloudapp.net/ISpellerService/SuggestCorrectionForSpecificWordRe" +
            "sponse")]
        WCFServiceWebRole.ATK.SuggestCorrectionForSpecificWordResponse SuggestCorrectionForSpecificWord(WCFServiceWebRole.ATK.SuggestCorrectionForSpecificWordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nlptoolkit.cloudapp.net/ISpellerService/SuggestCorrectionForSpecificWord", ReplyAction="http://nlptoolkit.cloudapp.net/ISpellerService/SuggestCorrectionForSpecificWordRe" +
            "sponse")]
        System.Threading.Tasks.Task<WCFServiceWebRole.ATK.SuggestCorrectionForSpecificWordResponse> SuggestCorrectionForSpecificWordAsync(WCFServiceWebRole.ATK.SuggestCorrectionForSpecificWordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nlptoolkit.cloudapp.net/ISpellerService/Autocorrect", ReplyAction="http://nlptoolkit.cloudapp.net/ISpellerService/AutocorrectResponse")]
        WCFServiceWebRole.ATK.AutocorrectResponse Autocorrect(WCFServiceWebRole.ATK.AutocorrectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nlptoolkit.cloudapp.net/ISpellerService/Autocorrect", ReplyAction="http://nlptoolkit.cloudapp.net/ISpellerService/AutocorrectResponse")]
        System.Threading.Tasks.Task<WCFServiceWebRole.ATK.AutocorrectResponse> AutocorrectAsync(WCFServiceWebRole.ATK.AutocorrectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nlptoolkit.cloudapp.net/ISpellerService/AutocorrectAndSuggest", ReplyAction="http://nlptoolkit.cloudapp.net/ISpellerService/AutocorrectAndSuggestResponse")]
        WCFServiceWebRole.ATK.AutocorrectAndSuggestResponse AutocorrectAndSuggest(WCFServiceWebRole.ATK.AutocorrectAndSuggestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nlptoolkit.cloudapp.net/ISpellerService/AutocorrectAndSuggest", ReplyAction="http://nlptoolkit.cloudapp.net/ISpellerService/AutocorrectAndSuggestResponse")]
        System.Threading.Tasks.Task<WCFServiceWebRole.ATK.AutocorrectAndSuggestResponse> AutocorrectAndSuggestAsync(WCFServiceWebRole.ATK.AutocorrectAndSuggestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nlptoolkit.cloudapp.net/ISpellerService/AutocorrectAndSuggest2", ReplyAction="http://nlptoolkit.cloudapp.net/ISpellerService/AutocorrectAndSuggest2Response")]
        WCFServiceWebRole.ATK.AutocorrectAndSuggest2Response AutocorrectAndSuggest2(WCFServiceWebRole.ATK.AutocorrectAndSuggest2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nlptoolkit.cloudapp.net/ISpellerService/AutocorrectAndSuggest2", ReplyAction="http://nlptoolkit.cloudapp.net/ISpellerService/AutocorrectAndSuggest2Response")]
        System.Threading.Tasks.Task<WCFServiceWebRole.ATK.AutocorrectAndSuggest2Response> AutocorrectAndSuggest2Async(WCFServiceWebRole.ATK.AutocorrectAndSuggest2Request request);
        
        // CODEGEN: Generating message contract since element name appId from namespace http://nlptoolkit.cloudapp.net is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nlptoolkit.cloudapp.net/ISpellerService/ReportWronglyDetectedWord", ReplyAction="http://nlptoolkit.cloudapp.net/ISpellerService/ReportWronglyDetectedWordResponse")]
        WCFServiceWebRole.ATK.ReportWronglyDetectedWordResponse ReportWronglyDetectedWord(WCFServiceWebRole.ATK.ReportWronglyDetectedWordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nlptoolkit.cloudapp.net/ISpellerService/ReportWronglyDetectedWord", ReplyAction="http://nlptoolkit.cloudapp.net/ISpellerService/ReportWronglyDetectedWordResponse")]
        System.Threading.Tasks.Task<WCFServiceWebRole.ATK.ReportWronglyDetectedWordResponse> ReportWronglyDetectedWordAsync(WCFServiceWebRole.ATK.ReportWronglyDetectedWordRequest request);
        
        // CODEGEN: Generating message contract since element name appId from namespace http://nlptoolkit.cloudapp.net is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://nlptoolkit.cloudapp.net/ISpellerService/SuggestMissingCorrection", ReplyAction="http://nlptoolkit.cloudapp.net/ISpellerService/SuggestMissingCorrectionResponse")]
        WCFServiceWebRole.ATK.SuggestMissingCorrectionResponse SuggestMissingCorrection(WCFServiceWebRole.ATK.SuggestMissingCorrectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nlptoolkit.cloudapp.net/ISpellerService/SuggestMissingCorrection", ReplyAction="http://nlptoolkit.cloudapp.net/ISpellerService/SuggestMissingCorrectionResponse")]
        System.Threading.Tasks.Task<WCFServiceWebRole.ATK.SuggestMissingCorrectionResponse> SuggestMissingCorrectionAsync(WCFServiceWebRole.ATK.SuggestMissingCorrectionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DetectMistakesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DetectMistakes", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public WCFServiceWebRole.ATK.DetectMistakesRequestBody Body;
        
        public DetectMistakesRequest() {
        }
        
        public DetectMistakesRequest(WCFServiceWebRole.ATK.DetectMistakesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class DetectMistakesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string inText;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool processLastWordOnly;
        
        public DetectMistakesRequestBody() {
        }
        
        public DetectMistakesRequestBody(string appId, string inText, bool processLastWordOnly) {
            this.appId = appId;
            this.inText = inText;
            this.processLastWordOnly = processLastWordOnly;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DetectMistakesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DetectMistakesResponse", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public WCFServiceWebRole.ATK.DetectMistakesResponseBody Body;
        
        public DetectMistakesResponse() {
        }
        
        public DetectMistakesResponse(WCFServiceWebRole.ATK.DetectMistakesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class DetectMistakesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public WCFServiceWebRole.ATK.SpellerErrorCode DetectMistakesResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public WCFServiceWebRole.ATK.ErroneousWord[] erroneousWords;
        
        public DetectMistakesResponseBody() {
        }
        
        public DetectMistakesResponseBody(WCFServiceWebRole.ATK.SpellerErrorCode DetectMistakesResult, WCFServiceWebRole.ATK.ErroneousWord[] erroneousWords) {
            this.DetectMistakesResult = DetectMistakesResult;
            this.erroneousWords = erroneousWords;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SuggestCorrectionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SuggestCorrections", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public WCFServiceWebRole.ATK.SuggestCorrectionsRequestBody Body;
        
        public SuggestCorrectionsRequest() {
        }
        
        public SuggestCorrectionsRequest(WCFServiceWebRole.ATK.SuggestCorrectionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class SuggestCorrectionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string inText;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public WCFServiceWebRole.ATK.SuggestionOption correctionOptions;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool processLastWordOnly;
        
        public SuggestCorrectionsRequestBody() {
        }
        
        public SuggestCorrectionsRequestBody(string appId, string inText, WCFServiceWebRole.ATK.SuggestionOption correctionOptions, bool processLastWordOnly) {
            this.appId = appId;
            this.inText = inText;
            this.correctionOptions = correctionOptions;
            this.processLastWordOnly = processLastWordOnly;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SuggestCorrectionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SuggestCorrectionsResponse", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public WCFServiceWebRole.ATK.SuggestCorrectionsResponseBody Body;
        
        public SuggestCorrectionsResponse() {
        }
        
        public SuggestCorrectionsResponse(WCFServiceWebRole.ATK.SuggestCorrectionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class SuggestCorrectionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public WCFServiceWebRole.ATK.SpellerErrorCode SuggestCorrectionsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public WCFServiceWebRole.ATK.ErroneousWord[] erroneousWords;
        
        public SuggestCorrectionsResponseBody() {
        }
        
        public SuggestCorrectionsResponseBody(WCFServiceWebRole.ATK.SpellerErrorCode SuggestCorrectionsResult, WCFServiceWebRole.ATK.ErroneousWord[] erroneousWords) {
            this.SuggestCorrectionsResult = SuggestCorrectionsResult;
            this.erroneousWords = erroneousWords;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReportCorrectionSelectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReportCorrectionSelection", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public WCFServiceWebRole.ATK.ReportCorrectionSelectionRequestBody Body;
        
        public ReportCorrectionSelectionRequest() {
        }
        
        public ReportCorrectionSelectionRequest(WCFServiceWebRole.ATK.ReportCorrectionSelectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class ReportCorrectionSelectionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string word;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string context;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string correction;
        
        public ReportCorrectionSelectionRequestBody() {
        }
        
        public ReportCorrectionSelectionRequestBody(string appId, string word, string context, string correction) {
            this.appId = appId;
            this.word = word;
            this.context = context;
            this.correction = correction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReportCorrectionSelectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReportCorrectionSelectionResponse", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public WCFServiceWebRole.ATK.ReportCorrectionSelectionResponseBody Body;
        
        public ReportCorrectionSelectionResponse() {
        }
        
        public ReportCorrectionSelectionResponse(WCFServiceWebRole.ATK.ReportCorrectionSelectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class ReportCorrectionSelectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public WCFServiceWebRole.ATK.SpellerErrorCode ReportCorrectionSelectionResult;
        
        public ReportCorrectionSelectionResponseBody() {
        }
        
        public ReportCorrectionSelectionResponseBody(WCFServiceWebRole.ATK.SpellerErrorCode ReportCorrectionSelectionResult) {
            this.ReportCorrectionSelectionResult = ReportCorrectionSelectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SuggestCorrectionForSpecificWordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SuggestCorrectionForSpecificWord", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public WCFServiceWebRole.ATK.SuggestCorrectionForSpecificWordRequestBody Body;
        
        public SuggestCorrectionForSpecificWordRequest() {
        }
        
        public SuggestCorrectionForSpecificWordRequest(WCFServiceWebRole.ATK.SuggestCorrectionForSpecificWordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class SuggestCorrectionForSpecificWordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string inText;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int wordPosition;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public WCFServiceWebRole.ATK.SuggestionOption correctionOptions;
        
        public SuggestCorrectionForSpecificWordRequestBody() {
        }
        
        public SuggestCorrectionForSpecificWordRequestBody(string appId, string inText, int wordPosition, WCFServiceWebRole.ATK.SuggestionOption correctionOptions) {
            this.appId = appId;
            this.inText = inText;
            this.wordPosition = wordPosition;
            this.correctionOptions = correctionOptions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SuggestCorrectionForSpecificWordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SuggestCorrectionForSpecificWordResponse", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public WCFServiceWebRole.ATK.SuggestCorrectionForSpecificWordResponseBody Body;
        
        public SuggestCorrectionForSpecificWordResponse() {
        }
        
        public SuggestCorrectionForSpecificWordResponse(WCFServiceWebRole.ATK.SuggestCorrectionForSpecificWordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class SuggestCorrectionForSpecificWordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public WCFServiceWebRole.ATK.SpellerErrorCode SuggestCorrectionForSpecificWordResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public WCFServiceWebRole.ATK.ErroneousWord erroneousWord;
        
        public SuggestCorrectionForSpecificWordResponseBody() {
        }
        
        public SuggestCorrectionForSpecificWordResponseBody(WCFServiceWebRole.ATK.SpellerErrorCode SuggestCorrectionForSpecificWordResult, WCFServiceWebRole.ATK.ErroneousWord erroneousWord) {
            this.SuggestCorrectionForSpecificWordResult = SuggestCorrectionForSpecificWordResult;
            this.erroneousWord = erroneousWord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutocorrectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Autocorrect", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public WCFServiceWebRole.ATK.AutocorrectRequestBody Body;
        
        public AutocorrectRequest() {
        }
        
        public AutocorrectRequest(WCFServiceWebRole.ATK.AutocorrectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class AutocorrectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string inText;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool processLastWordOnly;
        
        public AutocorrectRequestBody() {
        }
        
        public AutocorrectRequestBody(string appId, string inText, bool processLastWordOnly) {
            this.appId = appId;
            this.inText = inText;
            this.processLastWordOnly = processLastWordOnly;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutocorrectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutocorrectResponse", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public WCFServiceWebRole.ATK.AutocorrectResponseBody Body;
        
        public AutocorrectResponse() {
        }
        
        public AutocorrectResponse(WCFServiceWebRole.ATK.AutocorrectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class AutocorrectResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public WCFServiceWebRole.ATK.SpellerErrorCode AutocorrectResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string correctedText;
        
        public AutocorrectResponseBody() {
        }
        
        public AutocorrectResponseBody(WCFServiceWebRole.ATK.SpellerErrorCode AutocorrectResult, string correctedText) {
            this.AutocorrectResult = AutocorrectResult;
            this.correctedText = correctedText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutocorrectAndSuggestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutocorrectAndSuggest", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public WCFServiceWebRole.ATK.AutocorrectAndSuggestRequestBody Body;
        
        public AutocorrectAndSuggestRequest() {
        }
        
        public AutocorrectAndSuggestRequest(WCFServiceWebRole.ATK.AutocorrectAndSuggestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class AutocorrectAndSuggestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string inText;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool processLastWordOnly;
        
        public AutocorrectAndSuggestRequestBody() {
        }
        
        public AutocorrectAndSuggestRequestBody(string appId, string inText, bool processLastWordOnly) {
            this.appId = appId;
            this.inText = inText;
            this.processLastWordOnly = processLastWordOnly;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutocorrectAndSuggestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutocorrectAndSuggestResponse", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public WCFServiceWebRole.ATK.AutocorrectAndSuggestResponseBody Body;
        
        public AutocorrectAndSuggestResponse() {
        }
        
        public AutocorrectAndSuggestResponse(WCFServiceWebRole.ATK.AutocorrectAndSuggestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class AutocorrectAndSuggestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public WCFServiceWebRole.ATK.SpellerErrorCode AutocorrectAndSuggestResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string correctedText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public WCFServiceWebRole.ATK.ErroneousWord[] erroneousWords;
        
        public AutocorrectAndSuggestResponseBody() {
        }
        
        public AutocorrectAndSuggestResponseBody(WCFServiceWebRole.ATK.SpellerErrorCode AutocorrectAndSuggestResult, string correctedText, WCFServiceWebRole.ATK.ErroneousWord[] erroneousWords) {
            this.AutocorrectAndSuggestResult = AutocorrectAndSuggestResult;
            this.correctedText = correctedText;
            this.erroneousWords = erroneousWords;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutocorrectAndSuggest2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutocorrectAndSuggest2", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public WCFServiceWebRole.ATK.AutocorrectAndSuggest2RequestBody Body;
        
        public AutocorrectAndSuggest2Request() {
        }
        
        public AutocorrectAndSuggest2Request(WCFServiceWebRole.ATK.AutocorrectAndSuggest2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class AutocorrectAndSuggest2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string inText;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public WCFServiceWebRole.ATK.SuggestionOption correctionOptions;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool processLastWordOnly;
        
        public AutocorrectAndSuggest2RequestBody() {
        }
        
        public AutocorrectAndSuggest2RequestBody(string appId, string inText, WCFServiceWebRole.ATK.SuggestionOption correctionOptions, bool processLastWordOnly) {
            this.appId = appId;
            this.inText = inText;
            this.correctionOptions = correctionOptions;
            this.processLastWordOnly = processLastWordOnly;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutocorrectAndSuggest2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutocorrectAndSuggest2Response", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public WCFServiceWebRole.ATK.AutocorrectAndSuggest2ResponseBody Body;
        
        public AutocorrectAndSuggest2Response() {
        }
        
        public AutocorrectAndSuggest2Response(WCFServiceWebRole.ATK.AutocorrectAndSuggest2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class AutocorrectAndSuggest2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public WCFServiceWebRole.ATK.SpellerErrorCode AutocorrectAndSuggest2Result;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string correctedText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public WCFServiceWebRole.ATK.ErroneousWord[] erroneousWords;
        
        public AutocorrectAndSuggest2ResponseBody() {
        }
        
        public AutocorrectAndSuggest2ResponseBody(WCFServiceWebRole.ATK.SpellerErrorCode AutocorrectAndSuggest2Result, string correctedText, WCFServiceWebRole.ATK.ErroneousWord[] erroneousWords) {
            this.AutocorrectAndSuggest2Result = AutocorrectAndSuggest2Result;
            this.correctedText = correctedText;
            this.erroneousWords = erroneousWords;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReportWronglyDetectedWordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReportWronglyDetectedWord", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public WCFServiceWebRole.ATK.ReportWronglyDetectedWordRequestBody Body;
        
        public ReportWronglyDetectedWordRequest() {
        }
        
        public ReportWronglyDetectedWordRequest(WCFServiceWebRole.ATK.ReportWronglyDetectedWordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class ReportWronglyDetectedWordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string word;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string context;
        
        public ReportWronglyDetectedWordRequestBody() {
        }
        
        public ReportWronglyDetectedWordRequestBody(string appId, string word, string context) {
            this.appId = appId;
            this.word = word;
            this.context = context;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReportWronglyDetectedWordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReportWronglyDetectedWordResponse", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public WCFServiceWebRole.ATK.ReportWronglyDetectedWordResponseBody Body;
        
        public ReportWronglyDetectedWordResponse() {
        }
        
        public ReportWronglyDetectedWordResponse(WCFServiceWebRole.ATK.ReportWronglyDetectedWordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class ReportWronglyDetectedWordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public WCFServiceWebRole.ATK.SpellerErrorCode ReportWronglyDetectedWordResult;
        
        public ReportWronglyDetectedWordResponseBody() {
        }
        
        public ReportWronglyDetectedWordResponseBody(WCFServiceWebRole.ATK.SpellerErrorCode ReportWronglyDetectedWordResult) {
            this.ReportWronglyDetectedWordResult = ReportWronglyDetectedWordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SuggestMissingCorrectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SuggestMissingCorrection", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public WCFServiceWebRole.ATK.SuggestMissingCorrectionRequestBody Body;
        
        public SuggestMissingCorrectionRequest() {
        }
        
        public SuggestMissingCorrectionRequest(WCFServiceWebRole.ATK.SuggestMissingCorrectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class SuggestMissingCorrectionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string word;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string context;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string correction;
        
        public SuggestMissingCorrectionRequestBody() {
        }
        
        public SuggestMissingCorrectionRequestBody(string appId, string word, string context, string correction) {
            this.appId = appId;
            this.word = word;
            this.context = context;
            this.correction = correction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SuggestMissingCorrectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SuggestMissingCorrectionResponse", Namespace="http://nlptoolkit.cloudapp.net", Order=0)]
        public WCFServiceWebRole.ATK.SuggestMissingCorrectionResponseBody Body;
        
        public SuggestMissingCorrectionResponse() {
        }
        
        public SuggestMissingCorrectionResponse(WCFServiceWebRole.ATK.SuggestMissingCorrectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://nlptoolkit.cloudapp.net")]
    public partial class SuggestMissingCorrectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public WCFServiceWebRole.ATK.SpellerErrorCode SuggestMissingCorrectionResult;
        
        public SuggestMissingCorrectionResponseBody() {
        }
        
        public SuggestMissingCorrectionResponseBody(WCFServiceWebRole.ATK.SpellerErrorCode SuggestMissingCorrectionResult) {
            this.SuggestMissingCorrectionResult = SuggestMissingCorrectionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISpellerServiceChannel : WCFServiceWebRole.ATK.ISpellerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SpellerServiceClient : System.ServiceModel.ClientBase<WCFServiceWebRole.ATK.ISpellerService>, WCFServiceWebRole.ATK.ISpellerService {
        
        public SpellerServiceClient() {
        }
        
        public SpellerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SpellerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpellerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpellerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFServiceWebRole.ATK.DetectMistakesResponse WCFServiceWebRole.ATK.ISpellerService.DetectMistakes(WCFServiceWebRole.ATK.DetectMistakesRequest request) {
            return base.Channel.DetectMistakes(request);
        }
        
        public WCFServiceWebRole.ATK.SpellerErrorCode DetectMistakes(string appId, string inText, bool processLastWordOnly, out WCFServiceWebRole.ATK.ErroneousWord[] erroneousWords) {
            WCFServiceWebRole.ATK.DetectMistakesRequest inValue = new WCFServiceWebRole.ATK.DetectMistakesRequest();
            inValue.Body = new WCFServiceWebRole.ATK.DetectMistakesRequestBody();
            inValue.Body.appId = appId;
            inValue.Body.inText = inText;
            inValue.Body.processLastWordOnly = processLastWordOnly;
            WCFServiceWebRole.ATK.DetectMistakesResponse retVal = ((WCFServiceWebRole.ATK.ISpellerService)(this)).DetectMistakes(inValue);
            erroneousWords = retVal.Body.erroneousWords;
            return retVal.Body.DetectMistakesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCFServiceWebRole.ATK.DetectMistakesResponse> WCFServiceWebRole.ATK.ISpellerService.DetectMistakesAsync(WCFServiceWebRole.ATK.DetectMistakesRequest request) {
            return base.Channel.DetectMistakesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCFServiceWebRole.ATK.DetectMistakesResponse> DetectMistakesAsync(string appId, string inText, bool processLastWordOnly) {
            WCFServiceWebRole.ATK.DetectMistakesRequest inValue = new WCFServiceWebRole.ATK.DetectMistakesRequest();
            inValue.Body = new WCFServiceWebRole.ATK.DetectMistakesRequestBody();
            inValue.Body.appId = appId;
            inValue.Body.inText = inText;
            inValue.Body.processLastWordOnly = processLastWordOnly;
            return ((WCFServiceWebRole.ATK.ISpellerService)(this)).DetectMistakesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFServiceWebRole.ATK.SuggestCorrectionsResponse WCFServiceWebRole.ATK.ISpellerService.SuggestCorrections(WCFServiceWebRole.ATK.SuggestCorrectionsRequest request) {
            return base.Channel.SuggestCorrections(request);
        }
        
        public WCFServiceWebRole.ATK.SpellerErrorCode SuggestCorrections(string appId, string inText, WCFServiceWebRole.ATK.SuggestionOption correctionOptions, bool processLastWordOnly, out WCFServiceWebRole.ATK.ErroneousWord[] erroneousWords) {
            WCFServiceWebRole.ATK.SuggestCorrectionsRequest inValue = new WCFServiceWebRole.ATK.SuggestCorrectionsRequest();
            inValue.Body = new WCFServiceWebRole.ATK.SuggestCorrectionsRequestBody();
            inValue.Body.appId = appId;
            inValue.Body.inText = inText;
            inValue.Body.correctionOptions = correctionOptions;
            inValue.Body.processLastWordOnly = processLastWordOnly;
            WCFServiceWebRole.ATK.SuggestCorrectionsResponse retVal = ((WCFServiceWebRole.ATK.ISpellerService)(this)).SuggestCorrections(inValue);
            erroneousWords = retVal.Body.erroneousWords;
            return retVal.Body.SuggestCorrectionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCFServiceWebRole.ATK.SuggestCorrectionsResponse> WCFServiceWebRole.ATK.ISpellerService.SuggestCorrectionsAsync(WCFServiceWebRole.ATK.SuggestCorrectionsRequest request) {
            return base.Channel.SuggestCorrectionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCFServiceWebRole.ATK.SuggestCorrectionsResponse> SuggestCorrectionsAsync(string appId, string inText, WCFServiceWebRole.ATK.SuggestionOption correctionOptions, bool processLastWordOnly) {
            WCFServiceWebRole.ATK.SuggestCorrectionsRequest inValue = new WCFServiceWebRole.ATK.SuggestCorrectionsRequest();
            inValue.Body = new WCFServiceWebRole.ATK.SuggestCorrectionsRequestBody();
            inValue.Body.appId = appId;
            inValue.Body.inText = inText;
            inValue.Body.correctionOptions = correctionOptions;
            inValue.Body.processLastWordOnly = processLastWordOnly;
            return ((WCFServiceWebRole.ATK.ISpellerService)(this)).SuggestCorrectionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFServiceWebRole.ATK.ReportCorrectionSelectionResponse WCFServiceWebRole.ATK.ISpellerService.ReportCorrectionSelection(WCFServiceWebRole.ATK.ReportCorrectionSelectionRequest request) {
            return base.Channel.ReportCorrectionSelection(request);
        }
        
        public WCFServiceWebRole.ATK.SpellerErrorCode ReportCorrectionSelection(string appId, string word, string context, string correction) {
            WCFServiceWebRole.ATK.ReportCorrectionSelectionRequest inValue = new WCFServiceWebRole.ATK.ReportCorrectionSelectionRequest();
            inValue.Body = new WCFServiceWebRole.ATK.ReportCorrectionSelectionRequestBody();
            inValue.Body.appId = appId;
            inValue.Body.word = word;
            inValue.Body.context = context;
            inValue.Body.correction = correction;
            WCFServiceWebRole.ATK.ReportCorrectionSelectionResponse retVal = ((WCFServiceWebRole.ATK.ISpellerService)(this)).ReportCorrectionSelection(inValue);
            return retVal.Body.ReportCorrectionSelectionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCFServiceWebRole.ATK.ReportCorrectionSelectionResponse> WCFServiceWebRole.ATK.ISpellerService.ReportCorrectionSelectionAsync(WCFServiceWebRole.ATK.ReportCorrectionSelectionRequest request) {
            return base.Channel.ReportCorrectionSelectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCFServiceWebRole.ATK.ReportCorrectionSelectionResponse> ReportCorrectionSelectionAsync(string appId, string word, string context, string correction) {
            WCFServiceWebRole.ATK.ReportCorrectionSelectionRequest inValue = new WCFServiceWebRole.ATK.ReportCorrectionSelectionRequest();
            inValue.Body = new WCFServiceWebRole.ATK.ReportCorrectionSelectionRequestBody();
            inValue.Body.appId = appId;
            inValue.Body.word = word;
            inValue.Body.context = context;
            inValue.Body.correction = correction;
            return ((WCFServiceWebRole.ATK.ISpellerService)(this)).ReportCorrectionSelectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFServiceWebRole.ATK.SuggestCorrectionForSpecificWordResponse WCFServiceWebRole.ATK.ISpellerService.SuggestCorrectionForSpecificWord(WCFServiceWebRole.ATK.SuggestCorrectionForSpecificWordRequest request) {
            return base.Channel.SuggestCorrectionForSpecificWord(request);
        }
        
        public WCFServiceWebRole.ATK.SpellerErrorCode SuggestCorrectionForSpecificWord(string appId, string inText, int wordPosition, WCFServiceWebRole.ATK.SuggestionOption correctionOptions, out WCFServiceWebRole.ATK.ErroneousWord erroneousWord) {
            WCFServiceWebRole.ATK.SuggestCorrectionForSpecificWordRequest inValue = new WCFServiceWebRole.ATK.SuggestCorrectionForSpecificWordRequest();
            inValue.Body = new WCFServiceWebRole.ATK.SuggestCorrectionForSpecificWordRequestBody();
            inValue.Body.appId = appId;
            inValue.Body.inText = inText;
            inValue.Body.wordPosition = wordPosition;
            inValue.Body.correctionOptions = correctionOptions;
            WCFServiceWebRole.ATK.SuggestCorrectionForSpecificWordResponse retVal = ((WCFServiceWebRole.ATK.ISpellerService)(this)).SuggestCorrectionForSpecificWord(inValue);
            erroneousWord = retVal.Body.erroneousWord;
            return retVal.Body.SuggestCorrectionForSpecificWordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCFServiceWebRole.ATK.SuggestCorrectionForSpecificWordResponse> WCFServiceWebRole.ATK.ISpellerService.SuggestCorrectionForSpecificWordAsync(WCFServiceWebRole.ATK.SuggestCorrectionForSpecificWordRequest request) {
            return base.Channel.SuggestCorrectionForSpecificWordAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCFServiceWebRole.ATK.SuggestCorrectionForSpecificWordResponse> SuggestCorrectionForSpecificWordAsync(string appId, string inText, int wordPosition, WCFServiceWebRole.ATK.SuggestionOption correctionOptions) {
            WCFServiceWebRole.ATK.SuggestCorrectionForSpecificWordRequest inValue = new WCFServiceWebRole.ATK.SuggestCorrectionForSpecificWordRequest();
            inValue.Body = new WCFServiceWebRole.ATK.SuggestCorrectionForSpecificWordRequestBody();
            inValue.Body.appId = appId;
            inValue.Body.inText = inText;
            inValue.Body.wordPosition = wordPosition;
            inValue.Body.correctionOptions = correctionOptions;
            return ((WCFServiceWebRole.ATK.ISpellerService)(this)).SuggestCorrectionForSpecificWordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFServiceWebRole.ATK.AutocorrectResponse WCFServiceWebRole.ATK.ISpellerService.Autocorrect(WCFServiceWebRole.ATK.AutocorrectRequest request) {
            return base.Channel.Autocorrect(request);
        }
        
        public WCFServiceWebRole.ATK.SpellerErrorCode Autocorrect(string appId, string inText, bool processLastWordOnly, out string correctedText) {
            WCFServiceWebRole.ATK.AutocorrectRequest inValue = new WCFServiceWebRole.ATK.AutocorrectRequest();
            inValue.Body = new WCFServiceWebRole.ATK.AutocorrectRequestBody();
            inValue.Body.appId = appId;
            inValue.Body.inText = inText;
            inValue.Body.processLastWordOnly = processLastWordOnly;
            WCFServiceWebRole.ATK.AutocorrectResponse retVal = ((WCFServiceWebRole.ATK.ISpellerService)(this)).Autocorrect(inValue);
            correctedText = retVal.Body.correctedText;
            return retVal.Body.AutocorrectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCFServiceWebRole.ATK.AutocorrectResponse> WCFServiceWebRole.ATK.ISpellerService.AutocorrectAsync(WCFServiceWebRole.ATK.AutocorrectRequest request) {
            return base.Channel.AutocorrectAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCFServiceWebRole.ATK.AutocorrectResponse> AutocorrectAsync(string appId, string inText, bool processLastWordOnly) {
            WCFServiceWebRole.ATK.AutocorrectRequest inValue = new WCFServiceWebRole.ATK.AutocorrectRequest();
            inValue.Body = new WCFServiceWebRole.ATK.AutocorrectRequestBody();
            inValue.Body.appId = appId;
            inValue.Body.inText = inText;
            inValue.Body.processLastWordOnly = processLastWordOnly;
            return ((WCFServiceWebRole.ATK.ISpellerService)(this)).AutocorrectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFServiceWebRole.ATK.AutocorrectAndSuggestResponse WCFServiceWebRole.ATK.ISpellerService.AutocorrectAndSuggest(WCFServiceWebRole.ATK.AutocorrectAndSuggestRequest request) {
            return base.Channel.AutocorrectAndSuggest(request);
        }
        
        public WCFServiceWebRole.ATK.SpellerErrorCode AutocorrectAndSuggest(string appId, string inText, bool processLastWordOnly, out string correctedText, out WCFServiceWebRole.ATK.ErroneousWord[] erroneousWords) {
            WCFServiceWebRole.ATK.AutocorrectAndSuggestRequest inValue = new WCFServiceWebRole.ATK.AutocorrectAndSuggestRequest();
            inValue.Body = new WCFServiceWebRole.ATK.AutocorrectAndSuggestRequestBody();
            inValue.Body.appId = appId;
            inValue.Body.inText = inText;
            inValue.Body.processLastWordOnly = processLastWordOnly;
            WCFServiceWebRole.ATK.AutocorrectAndSuggestResponse retVal = ((WCFServiceWebRole.ATK.ISpellerService)(this)).AutocorrectAndSuggest(inValue);
            correctedText = retVal.Body.correctedText;
            erroneousWords = retVal.Body.erroneousWords;
            return retVal.Body.AutocorrectAndSuggestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCFServiceWebRole.ATK.AutocorrectAndSuggestResponse> WCFServiceWebRole.ATK.ISpellerService.AutocorrectAndSuggestAsync(WCFServiceWebRole.ATK.AutocorrectAndSuggestRequest request) {
            return base.Channel.AutocorrectAndSuggestAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCFServiceWebRole.ATK.AutocorrectAndSuggestResponse> AutocorrectAndSuggestAsync(string appId, string inText, bool processLastWordOnly) {
            WCFServiceWebRole.ATK.AutocorrectAndSuggestRequest inValue = new WCFServiceWebRole.ATK.AutocorrectAndSuggestRequest();
            inValue.Body = new WCFServiceWebRole.ATK.AutocorrectAndSuggestRequestBody();
            inValue.Body.appId = appId;
            inValue.Body.inText = inText;
            inValue.Body.processLastWordOnly = processLastWordOnly;
            return ((WCFServiceWebRole.ATK.ISpellerService)(this)).AutocorrectAndSuggestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFServiceWebRole.ATK.AutocorrectAndSuggest2Response WCFServiceWebRole.ATK.ISpellerService.AutocorrectAndSuggest2(WCFServiceWebRole.ATK.AutocorrectAndSuggest2Request request) {
            return base.Channel.AutocorrectAndSuggest2(request);
        }
        
        public WCFServiceWebRole.ATK.SpellerErrorCode AutocorrectAndSuggest2(string appId, string inText, WCFServiceWebRole.ATK.SuggestionOption correctionOptions, bool processLastWordOnly, out string correctedText, out WCFServiceWebRole.ATK.ErroneousWord[] erroneousWords) {
            WCFServiceWebRole.ATK.AutocorrectAndSuggest2Request inValue = new WCFServiceWebRole.ATK.AutocorrectAndSuggest2Request();
            inValue.Body = new WCFServiceWebRole.ATK.AutocorrectAndSuggest2RequestBody();
            inValue.Body.appId = appId;
            inValue.Body.inText = inText;
            inValue.Body.correctionOptions = correctionOptions;
            inValue.Body.processLastWordOnly = processLastWordOnly;
            WCFServiceWebRole.ATK.AutocorrectAndSuggest2Response retVal = ((WCFServiceWebRole.ATK.ISpellerService)(this)).AutocorrectAndSuggest2(inValue);
            correctedText = retVal.Body.correctedText;
            erroneousWords = retVal.Body.erroneousWords;
            return retVal.Body.AutocorrectAndSuggest2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCFServiceWebRole.ATK.AutocorrectAndSuggest2Response> WCFServiceWebRole.ATK.ISpellerService.AutocorrectAndSuggest2Async(WCFServiceWebRole.ATK.AutocorrectAndSuggest2Request request) {
            return base.Channel.AutocorrectAndSuggest2Async(request);
        }
        
        public System.Threading.Tasks.Task<WCFServiceWebRole.ATK.AutocorrectAndSuggest2Response> AutocorrectAndSuggest2Async(string appId, string inText, WCFServiceWebRole.ATK.SuggestionOption correctionOptions, bool processLastWordOnly) {
            WCFServiceWebRole.ATK.AutocorrectAndSuggest2Request inValue = new WCFServiceWebRole.ATK.AutocorrectAndSuggest2Request();
            inValue.Body = new WCFServiceWebRole.ATK.AutocorrectAndSuggest2RequestBody();
            inValue.Body.appId = appId;
            inValue.Body.inText = inText;
            inValue.Body.correctionOptions = correctionOptions;
            inValue.Body.processLastWordOnly = processLastWordOnly;
            return ((WCFServiceWebRole.ATK.ISpellerService)(this)).AutocorrectAndSuggest2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFServiceWebRole.ATK.ReportWronglyDetectedWordResponse WCFServiceWebRole.ATK.ISpellerService.ReportWronglyDetectedWord(WCFServiceWebRole.ATK.ReportWronglyDetectedWordRequest request) {
            return base.Channel.ReportWronglyDetectedWord(request);
        }
        
        public WCFServiceWebRole.ATK.SpellerErrorCode ReportWronglyDetectedWord(string appId, string word, string context) {
            WCFServiceWebRole.ATK.ReportWronglyDetectedWordRequest inValue = new WCFServiceWebRole.ATK.ReportWronglyDetectedWordRequest();
            inValue.Body = new WCFServiceWebRole.ATK.ReportWronglyDetectedWordRequestBody();
            inValue.Body.appId = appId;
            inValue.Body.word = word;
            inValue.Body.context = context;
            WCFServiceWebRole.ATK.ReportWronglyDetectedWordResponse retVal = ((WCFServiceWebRole.ATK.ISpellerService)(this)).ReportWronglyDetectedWord(inValue);
            return retVal.Body.ReportWronglyDetectedWordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCFServiceWebRole.ATK.ReportWronglyDetectedWordResponse> WCFServiceWebRole.ATK.ISpellerService.ReportWronglyDetectedWordAsync(WCFServiceWebRole.ATK.ReportWronglyDetectedWordRequest request) {
            return base.Channel.ReportWronglyDetectedWordAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCFServiceWebRole.ATK.ReportWronglyDetectedWordResponse> ReportWronglyDetectedWordAsync(string appId, string word, string context) {
            WCFServiceWebRole.ATK.ReportWronglyDetectedWordRequest inValue = new WCFServiceWebRole.ATK.ReportWronglyDetectedWordRequest();
            inValue.Body = new WCFServiceWebRole.ATK.ReportWronglyDetectedWordRequestBody();
            inValue.Body.appId = appId;
            inValue.Body.word = word;
            inValue.Body.context = context;
            return ((WCFServiceWebRole.ATK.ISpellerService)(this)).ReportWronglyDetectedWordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFServiceWebRole.ATK.SuggestMissingCorrectionResponse WCFServiceWebRole.ATK.ISpellerService.SuggestMissingCorrection(WCFServiceWebRole.ATK.SuggestMissingCorrectionRequest request) {
            return base.Channel.SuggestMissingCorrection(request);
        }
        
        public WCFServiceWebRole.ATK.SpellerErrorCode SuggestMissingCorrection(string appId, string word, string context, string correction) {
            WCFServiceWebRole.ATK.SuggestMissingCorrectionRequest inValue = new WCFServiceWebRole.ATK.SuggestMissingCorrectionRequest();
            inValue.Body = new WCFServiceWebRole.ATK.SuggestMissingCorrectionRequestBody();
            inValue.Body.appId = appId;
            inValue.Body.word = word;
            inValue.Body.context = context;
            inValue.Body.correction = correction;
            WCFServiceWebRole.ATK.SuggestMissingCorrectionResponse retVal = ((WCFServiceWebRole.ATK.ISpellerService)(this)).SuggestMissingCorrection(inValue);
            return retVal.Body.SuggestMissingCorrectionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCFServiceWebRole.ATK.SuggestMissingCorrectionResponse> WCFServiceWebRole.ATK.ISpellerService.SuggestMissingCorrectionAsync(WCFServiceWebRole.ATK.SuggestMissingCorrectionRequest request) {
            return base.Channel.SuggestMissingCorrectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCFServiceWebRole.ATK.SuggestMissingCorrectionResponse> SuggestMissingCorrectionAsync(string appId, string word, string context, string correction) {
            WCFServiceWebRole.ATK.SuggestMissingCorrectionRequest inValue = new WCFServiceWebRole.ATK.SuggestMissingCorrectionRequest();
            inValue.Body = new WCFServiceWebRole.ATK.SuggestMissingCorrectionRequestBody();
            inValue.Body.appId = appId;
            inValue.Body.word = word;
            inValue.Body.context = context;
            inValue.Body.correction = correction;
            return ((WCFServiceWebRole.ATK.ISpellerService)(this)).SuggestMissingCorrectionAsync(inValue);
        }
    }
}
